server {
  listen 80;
  location / {
    # Forward to the lotus container
    proxy_pass http://lotus:1234;

    # Inject CORS headers
    # add_header Access-Control-Allow-Origin  *           always;
    # add_header Access-Control-Allow-Methods GET,POST,OPTIONS always;
    # add_header Access-Control-Allow-Headers Content-Type,Authorization always;

    add_header 'Access-Control-Allow-Origin' * always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

    # Answer preflight immediately
    if ($request_method = OPTIONS) {
      return 204;
    }
  }
}
